# Метод якобинского клуба.

In [1]:
import numpy as np

Некто матрица поворота:

In [2]:
def Rot ( i , j , N , s ):
    
    Q = np.eye(N)
    
    Q[i][i] =   np.cos(s)
    Q[j][j] =   np.cos(s)
    Q[i][j] = - np.sin(s)
    Q[j][i] =   np.sin(s)
    
    return Q

Некто метод Якоби:

In [3]:
def Jac ( A, k = 27182 , tol = 1e-6 ):
    
    N = A.shape[0]
    
    p = 0
    
    while p < k:
        
        p += 1
        
        d = tol
        
        for i in range (N):
            
            for j in range ( i + 1 , N ):
                
                if ( np.abs ( A [i , j] ) > d ) :
                    
                    d = np.abs ( A [i , j] )
                    
                    s = np.arctan ( 2 * A [i , j] / ( A [j , j] - A [i , i] ) ) / 2.
                    
                G = Rot ( i , j , N , s )
            
                A = G @ A @ G.T
    
    return np.diagonal ( A )

Некто идеальное сходство:

In [4]:
W = np.array ( [ [ 4 , 2 , 3 ] , [ 2 , 9 , 7 ] , [ 3 , 7 , 1 ] ] )  


print( W , Jac(W) )

[[4 2 3]
 [2 9 7]
 [3 7 1]] [ 3.32165664 14.11279946 -3.43445609]


In [5]:
np.linalg.eigvals(W)

array([14.11279946,  3.32165664, -3.43445609])