In [2]:
import numpy as np

from numpy.testing import assert_allclose

# Part I. Construct a Householder reflection of a vector.

Given a vector $\mathbf{x}$, and a plane with a normal vector $\mathbf{u}$, the Householder transformation reflects $\mathbf{x}$ about the plane.

The matrix of the Householder transformation is

$$
\mathbf{H} = \mathbf{1} - 2 \mathbf{u} \mathbf{u}^T
$$

Given two equal-length vectors $\mathbf{x}$ and $\mathbf{y}$, a rotation which brings $\mathbf{x}$ to $\mathbf{y}$ is a Householder transform with

$$
\mathbf{u} = \frac{\mathbf{x} - \mathbf{y}}{||\mathbf{x} - \mathbf{y}||}
$$

In [189]:
def householder(vec):
    """Construct a Householder reflection to zero out 2nd and further components of a vector.

    Parameters
    ----------
    vec : array-like of floats, shape (n,)
        Input vector
    
    Returns
    -------
    outvec : array of floats, shape (n,)
        Transformed vector, with ``outvec[1:]==0`` and ``|outvec| == |vec|``
    H : array of floats, shape (n, n)
        Orthogonal matrix of the Householder reflection
    """
    vec = np.asarray(vec, dtype=float)
    if vec.ndim != 1:
        raise ValueError("vec.ndim = %s, expected 1" % vec.ndim)
        
    n = vec.shape[0]    
        
    vec = np.reshape( vec, ( n , 1 ) )
    
    desire = np.zeros_like(vec)
    
    norm = np.linalg.norm ( vec )
    
    desire[0] = norm
    
    u = ( vec - desire ) / np.linalg.norm ( vec - desire )
    
    H = np.identity(n) - 2 * u @ u.T
    
    outvec = H @ vec
    
    for i in range (n) : #избавляюсь от величин порядка машинного епсилен
        
        if np.abs( outvec[i] ) < 1e-15:
            
            outvec[i] = 0
            
    outvec = np.reshape(outvec, (n,) )        
    
    return outvec, H

In [190]:
# Test (marked)

v = np.array([1, 2, 3])
v1, h = householder(v)

assert_allclose(np.dot(h, v1), v)
assert_allclose(np.dot(h, v), v1)

# тест пройден


In [191]:
rndm = np.random.RandomState(1234)

vec = rndm.uniform(size=7)
v1, h = householder(vec)

assert_allclose(np.dot(h, v1), vec)

#тест пройден

# Part II. Compute the QR decomposition of a matrix.

Given a rectangular $m\times n$ matrix $\mathbf{A}$, construct a Householder reflector matrix $\mathbf{H}_1$ which transforms the first column of $\mathbf{A}$ (and call the result $\mathbf{A}^{(1)}$)

$$
\mathbf{H}_1 \mathbf{A} =%
\begin{pmatrix}
\times & \times & \times & \dots & \times \\
0      & \times & \times & \dots & \times \\
0      & \times & \times & \dots & \times \\
&& \dots&& \\
0      & \times & \times & \dots & \times \\
\end{pmatrix}%
\equiv \mathbf{A}^{(1)}\;.
$$

Now consider the lower-right submatrix of $\mathbf{A}^{(1)}$, and construct a Householder reflector which annihilates the second column of $\mathbf{A}$:

$$
\mathbf{H}_2 \mathbf{A}^{(1)} =%
\begin{pmatrix}
\times & \times & \times & \dots & \times \\
0      & \times & \times & \dots & \times \\
0      & 0      & \times & \dots & \times \\
&& \dots&& \\
0      & 0      & \times & \dots & \times \\
\end{pmatrix}%
\equiv \mathbf{A}^{(2)} \;.
$$

Repeating the process $n-1$ times, we obtain

$$
\mathbf{H}_{n-1} \cdots \mathbf{H}_2 \mathbf{H}_1 \mathbf{A} = \mathbf{R} \;,
$$

with $\mathbf{R}$ an upper triangular matrix. Since each $\mathbf{H}_k$ is orthogonal, so is their product. The inverse of an orthogonal matrix is orthogonal. Hence the process generates the $QR$ decomposition of $\mathbf{A}$. 

In [192]:
def qr_decomp(a1):
    """Compute the QR decomposition of a matrix.
    
    Parameters
    ----------
    a : ndarray, shape(m, n)
        The input matrix
    
    Returns
    -------
    q : ndarray, shape(m, m)
        The orthogonal matrix
    r : ndarray, shape(m, n)
        The upper triangular matrix
        
    Examples
    --------
    >>> a = np.random.random(size=(3, 5))
    >>> q, r = qr_decomp(a)
    >>> np.assert_allclose(np.dot(q, r), a)
    
    """
    
    
    a = np.array(a1, copy=True, dtype=float)
    
    m, n = a1.shape
    
    Eye = np.identity ( m )
    
    Q = Eye
    
    for i in range ( n ): 
        
        stolb = a [i: , i]
        
        H = np.zeros( (m,m) )
        
        H[i:,i:] = householder( stolb ) [1]
        
        H[:i,:i] = np.identity (i)
                     
        Q = Q @ H
        
        a = H @ a
    
    return Q, a

In [193]:
# Might want to turn this on for prettier printing: zeros instead of `1e-16` etc

np.set_printoptions(suppress=True)

In [194]:
# Test (marked)

rndm = np.random.RandomState(1234)
a = rndm.uniform(size=(5, 3))
q, r = qr_decomp(a)

# test that Q is indeed orthogonal
assert_allclose(np.dot(q, q.T), np.eye(5), atol=1e-10)

# test the decomposition itself
assert_allclose(np.dot(q, r), a)

#тест пройден

Now compare your decompositions to the library function (which actually wraps the corresponding LAPACK functions)

In [195]:
from scipy.linalg import qr
qq, rr = qr(a)

assert_allclose(np.dot(qq, rr), a)

print(q)
print()
print(qq)
print()
print(r)
print()
print(rr)

[[-0.13665049 -0.53601299  0.09369752  0.53884211 -0.62840009]
 [-0.56035895 -0.0935397   0.53326881  0.30845142  0.54564665]
 [-0.19725922 -0.65948912 -0.60068463 -0.17180277  0.368544  ]
 [-0.62498418  0.50418303 -0.52144688  0.22920996 -0.17535732]
 [-0.48765568 -0.12171264  0.27224305 -0.72969412 -0.37524417]]

[[-0.13665049  0.53601299  0.09369752  0.661619   -0.49749149]
 [-0.56035895  0.0935397   0.53326881 -0.52477245 -0.34276292]
 [-0.19725922  0.65948912 -0.60068463 -0.37879015  0.14784752]
 [-0.62498418 -0.50418303 -0.52144688  0.18967657 -0.21750907]
 [-0.48765568  0.12171264  0.27224305  0.32774225  0.75222783]]

[[-1.40152769 -1.2514379  -0.89523615]
 [-0.         -0.84158252 -0.68447942]
 [ 0.         -0.         -0.5496046 ]
 [ 0.         -0.         -0.        ]
 [-0.         -0.          0.        ]]

[[-1.40152769 -1.2514379  -0.89523615]
 [ 0.          0.84158252  0.68447942]
 [ 0.          0.         -0.5496046 ]
 [ 0.          0.          0.        ]
 [ 0.        

Check if your `q` and `r` agree with `qq` and `rr`. Explain.

Я же русский человек.

Для знаков в q и r очевидно: задача о занулении всех коэффициентов вектора с сохранением нормы неоднозначна с точностью до знака. Специалисты numpy почему-то предпочли -H.

На то, что столбцы разные, ответ тоже очень прост: QR - разложение в общем случае не единственно. Кто знает, какие алгоритмы используются в numpy. Так или иначе, нет ничего удивительного в том, что они приводят к другому ответу. Потому что он возможен.

# Part III. Avoid forming Householder matrices explicitly.

Note the special structure of the Householder matrices: A reflector $\mathbf{H}$ is completely specified by a reflection vector $\mathbf{u}$. Also note that the computational cost of applying a reflector to a matrix strongly depends on the order of operations:

$$
\left( \mathbf{u} \mathbf{u}^T \right) \mathbf{A}  \qquad \textrm{is } O(m^2 n)\;,
$$
while
$$
\mathbf{u} \left( \mathbf{u}^T \mathbf{A} \right) \qquad \textrm{is } O(mn)
$$

Thus, it seems to make sense to *avoid* forming the $\mathbf{H}$ matrices. Instead, one stores the reflection vectors, $\mathbf{u}$, themselves, and provides a way of multiplying an arbitrary matrix by $\mathbf{Q}^T$, e.g., as a standalone function (or a class).

Write a function which constructs the `QR` decomposition of a matrix *without ever forming the* $\mathbf{H}$ matrices, and returns the $\mathbf{R}$ matrix and reflection vectors. Write a second function, which uses the reflection vertices to multiply a matrix with $\mathbf{Q}^T$. Make sure to include enough comments for a marker to follow your implementation, and add tests.

In [221]:
def u (vec):
    
    vec = np.asarray(vec, dtype=float)
    
    if vec.ndim != 1:
        raise ValueError("vec.ndim = %s, expected 1" % vec.ndim)
        
    n = vec.shape[0]    
        
    vec = np.reshape( vec, ( n , 1 ) )
    
    desire = np.zeros_like(vec)
    
    norm = np.linalg.norm ( vec )
    
    desire[0] = norm
    
    u = ( vec - desire ) / np.linalg.norm ( vec - desire )    
    
    return u


def QR(a1):  
    
    a = np.array(a1, copy=True, dtype=float)
    
    m, n = a1.shape
    
    Q = np.identity ( m )
    
    for i in range ( n ): 
        
        stolb = a [i: , i]
                     
        Q[i:,i:] =  Q[i:,i:] - 2 * Q[i:,i:] @ u(stolb) @ u(stolb).T
        
        a[i:,i:] = a[i:,i:] - 2 * u(stolb) @ u(stolb).T @ a[i:,i:]
    
    return Q, a